MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  DEVICE: "cuda"
  ATTRIBUTE_ON: False
  RELATION_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
  FPN:
    USE_GN: False
    USE_RELU: False
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    ANCHOR_STRIDE: (4,8,16,32,64)
    ASPECT_RATIOS: (0.5, 1.0, 2.0)
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FPN_POST_NMS_PER_BATCH: True
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 1200
  ROI_ATTRIBUTE_HEAD:
    NUM_ATTRIBUTES: 0
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64  
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    BG_IOU_THRESHOLD: 0.3
    DETECTIONS_PER_IMG: 256
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.3
    NMS_FILTER_DUPLICATES: False
    POSITIVE_FRACTION: 0.25
    POST_NMS_PER_CLS_TOPN: 300
    SCORE_THRESH: 0.01
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: "ResNet50Conv5ROIFeatureExtractor"
    PREDICTOR: "FastRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    NUM_CLASSES: 4
    MLP_HEAD_DIM: 2048
    CONV_HEAD_DIM: 256
    NUM_STACKED_CONVS: 4
    USE_GN: False
  ROI_RELATION_HEAD:
    CONTEXT_POOLING_DIM: 12
    CONTEXT_HIDDEN_DIM: 512
    CONTEXT_OBJ_LAYER: 1
    CONTEXT_REL_LAYER: 1
    FEATURE_EXTRACTOR: "RelationFeatureExtractor"
    PREDICTOR: "MotifPredictor"
    NUM_CLASSES: 5
    USE_GT_BOX: True
    USE_GT_OBJECT_LABEL: False
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  STEPS: (1000, 2000)
  MAX_ITER: 10000
  IMS_PER_BATCH: 2
DATASETS:
  TRAIN: ("my_dataset_train",)
  TEST: ("my_dataset_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 850
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 850
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
  PIXEL_STD: [1.0, 1.0, 1.0]
  TO_BGR255: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
OUTPUT_DIR: "/work/rleap1/nirmal.aheshwari/Pong"
DTYPE: "float32"

